Client_App/config/routes.rb
Rails.application.routes.draw do
  get 'price' => 'price#index'

  get 'about' => 'about#index'

  get 'home' => 'home#index'
  root 'home#index'

  resources :contacts
  get 'contact', to: 'contacts#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Client_App/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Client_App/app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

Client_App/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Client_App/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new; end
end

Client_App/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

Client_App/app/controllers/price_controller.rb
class PriceController < ApplicationController
  def index
  end
end

Client_App/app/helpers/about_helper.rb
module AboutHelper
end

Client_App/app/helpers/application_helper.rb
module ApplicationHelper
end

Client_App/app/helpers/home_helper.rb
module HomeHelper
end

Client_App/app/helpers/price_helper.rb
module PriceHelper
end

Client_App/app/views/about/index.html.erb
<script>
  getPageInformations();
  updateDataInRDStationApp();
</script>

<h1>About</h1>

Client_App/app/views/contacts/new.html.erb
<script>
  getPageInformations();
  updateDataInRDStationApp();
</script>

<h1>Contact</h1>

<!--<form action="/action_page.php">
  E-mail:<br>
  <input type="text" name="E-mail" value="linus@linux.com">
  <br>
  <button type="button">Click Me!</button>
</form>-->

<%= form_for :contact do |f| %>
  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email, :value => "linus@linux.com", :required => true %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<script>
$('form').submit(function() {
    sendDataToRDStationApp($(this).serialize());
    return false;
});
</script>

Client_App/app/views/home/index.html.erb
<script>
  getPageInformations();
  updateDataInRDStationApp();
</script>

<h1>Bem vindo a página inicial do cliente - HOME</h1>

Client_App/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClientApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<script type="text/javascript" src="https://cdn.rawgit.com/josepedro/RD_test/master/track_library.js"></script>
  <header class="navbar navbar-fixed-top navbar-inverse">
 <div class="container">
   <nav>
     <tr>
       <td><%= link_to 'Home', home_url %></td>
       <td><%= link_to 'About', '\about' %></td>
       <td><%= link_to 'Price', '\price' %></td>
       <td><%= link_to 'Contact', '\contact' %></td>
     </tr>


   </nav>
 </div>
</header>

  <body>
    <%= yield %>
  </body>
</html>

Client_App/app/views/price/index.html.erb
<script>
  getPageInformations();
  updateDataInRDStationApp();
</script>

<h1>Price</h1>